code --install-extension EditorConfig.EditorConfig
code --install-extension GitHub.vscode-pull-request-github
code --install-extension JannisX11.batch-rename-extension
code --install-extension KevinRose.vsc-python-indent
code --install-extension Tyriar.sort-lines
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension arturock.gitstash
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension batisteo.vscode-django
code --install-extension bibhasdn.unique-lines
code --install-extension bungcip.better-toml
code --install-extension codezombiech.gitignore
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension eamodio.gitlens
code --install-extension earshinov.permute-lines
code --install-extension esbenp.prettier-vscode
code --install-extension gera2ld.markmap-vscode
code --install-extension golang.go
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension humao.rest-client
code --install-extension janisdd.vscode-edit-csv
code --install-extension jebbs.plantuml
code --install-extension joaompinto.asciidoctor-vscode
code --install-extension kevinchatham.openwithcode
code --install-extension magicstack.MagicPython
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.test-adapter-converter
code --install-extension njpwerner.autodocstring
code --install-extension redhat.vscode-xml
code --install-extension richie5um2.vscode-sort-json
code --install-extension rogalmic.vscode-xml-complete
code --install-extension rust-lang.rust-analyzer
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension shardulm94.trailing-spaces
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension tamasfe.even-better-toml
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension tomoki1207.vscode-input-sequence
code --install-extension wholroyd.jinja
code --install-extension wmaurer.change-case
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
