code --install-extension alefragnani.project-manager
code --install-extension arturock.gitstash
code --install-extension asciidoctor.asciidoctor-vscode
code --install-extension bibhasdn.unique-lines
code --install-extension codezombiech.gitignore
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension eamodio.gitlens
code --install-extension earshinov.permute-lines
code --install-extension editorconfig.editorconfig
code --install-extension emilast.logfilehighlighter
code --install-extension erd0s.terraform-autocomplete
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension gera2ld.markmap-vscode
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.vscode-pull-request-github
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension hashicorp.terraform
code --install-extension hbenl.vscode-test-explorer
code --install-extension hediet.vscode-drawio
code --install-extension humao.rest-client
code --install-extension ibm.output-colorizer
code --install-extension janisdd.vscode-edit-csv
code --install-extension jannisx11.batch-rename-extension
code --install-extension jebbs.plantuml
code --install-extension kevinchatham.openwithcode
code --install-extension kevinrose.vsc-python-indent
code --install-extension lyrise1984.vscode-rocket-pack
code --install-extension magicstack.magicpython
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-ceintl.vscode-language-pack-ja
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.remote-explorer
code --install-extension ms-vscode.remote-server
code --install-extension ms-vscode.test-adapter-converter
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension richie5um2.vscode-sort-json
code --install-extension rogalmic.vscode-xml-complete
code --install-extension rust-lang.rust-analyzer
code --install-extension ryuta46.multi-command
code --install-extension scala-lang.scala
code --install-extension scalameta.metals
code --install-extension shardulm94.trailing-spaces
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension sumneko.lua
code --install-extension tamasfe.even-better-toml
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension tomoki1207.pdf
code --install-extension tomoki1207.vscode-input-sequence
code --install-extension tyriar.sort-lines
code --install-extension usernamehw.errorlens
code --install-extension visualstudioexptteam.intellicode-api-usage-examples
code --install-extension visualstudioexptteam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension wholroyd.jinja
code --install-extension wmaurer.change-case
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
