#!/bin/bash

while read local_ref local_sha1 remote_ref remote_sha1
do
	branch=${remote_ref#refs/heads/}
	case "$branch" in
		"main" | "master" | "develop")
			toilet -t -f mono12 -- "-> $branch"

			echo -en "\033[33mWarning: maybe you don't want to push to 🌳 \033[31;1m$branch \033[m\033[33mbranch 🌳. Continue? [y/N]: \033[m"

            exec < /dev/tty
            read ANSWER

            case $ANSWER in
                "Y" | "y" | "yes" | "Yes" | "YES" ) echo "OK. commit start.";;
                * ) echo "commit failed.";exit 1;;
            esac
            exit 0
            ;;
	esac
done

# call original
. `dirname ${0}`/_local-hook-exec
